<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>CbtIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\CbtIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="CbtIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\CbtIcon.ico" />
    <Resource Include="Assets\Images\polinema-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="ManagedNativeWifi" Version="3.0.2" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

</Project>
